<a href="https://colab.research.google.com/github/safayetsawom/pytorch_deeplearning_practice/blob/main/pytorch__dl.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#tensors used as multi-dimensional matrix
import torch
import numpy as np
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)
np_array = np.array(data)
# x_np = torch.from_numpy(np_array)
print(np_array)
print(data)

tensor([[1, 2],
        [3, 4]])
[[1 2]
 [3 4]]
[[1, 2], [3, 4]]


In [ ]:
np1=np.random.rand(2,4) #2 row and 4 column
np2=np.random.rand(3,2,4)
print(np1)
print("----------------------------------")
print(np2)
print("----------------------------------")
print(torch.randn(2,4))

[[0.14490339 0.21825624 0.65632829 0.0397975 ]
 [0.73751387 0.63763408 0.6614644  0.69687261]]
----------------------------------
[[[0.86223101 0.50328904 0.59010082 0.19944229]
  [0.32823254 0.87614024 0.71352438 0.19777112]]

 [[0.29844281 0.58473411 0.84990886 0.2118064 ]
  [0.89383008 0.82550705 0.16822605 0.46338569]]

 [[0.95023334 0.89196215 0.18396692 0.65528753]
  [0.86645005 0.58351494 0.23628229 0.17183018]]]
----------------------------------
tensor([[-0.8224,  2.2238, -0.7454, -0.2964],
        [-1.0978, -0.2372, -0.8483,  1.2948]])


In [ ]:
tensor3d=torch.zeros(2,3,4)
print(tensor3d)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


tensor operations


In [ ]:
torch_1=torch.arange(10)
torch_1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
torch_1=torch_1.reshape(2,5)
torch_1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
torch_1=torch_1.reshape(-1,5) #if i don't know how many array will occur then use -1
torch_1

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
torch_2=torch_1.reshape(2,5)
print(torch_2)
torch_3=torch_1.view(2,5)
print(torch_3)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [ ]:
import torch

# Create a tensor
x = torch.randn(3, 4)

# View (compatible shape, contiguous tensor)
y = x.view(3,4)  # shares memory with x

# Reshape (incompatible shape, non-contiguous tensor)
z = x.reshape(4, 3)  # creates a copy of x
print(y)
print(z)


tensor([[-1.3755, -0.5521,  2.2498, -0.2471],
        [ 1.2465,  0.2241,  1.5626, -1.1535],
        [ 0.8046,  0.3569,  0.2948, -0.9325]])
tensor([[-1.3755, -0.5521,  2.2498],
        [-0.2471,  1.2465,  0.2241],
        [ 1.5626, -1.1535,  0.8046],
        [ 0.3569,  0.2948, -0.9325]])


In [ ]:
my_torch3=torch.arange(10)
my_torch3
my_torch4=my_torch3.reshape(5,2)
print(my_torch4)
print(my_torch4[:2]) #first 2 row
print(my_torch4[:,1]) #second column horizontally
print(my_torch4[1:3,1]) #second and third row and second column
print(my_torch4[:,1:]) #second column vertically

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])
tensor([[0, 1],
        [2, 3]])
tensor([1, 3, 5, 7, 9])
tensor([3, 5])
tensor([[1],
        [3],
        [5],
        [7],
        [9]])


math operations


In [ ]:
tensor_a= torch.tensor([1,2,3,4,5])
tensor_b= torch.tensor([7,8,9,10,11])
print(tensor_a)
print(tensor_a+tensor_b)
print(torch.add(tensor_a,tensor_b))

tensor([1, 2, 3, 4, 5])
tensor([ 8, 10, 12, 14, 16])
tensor([ 8, 10, 12, 14, 16])
